---

- name: Install dovecot packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ dovecot_apt_pkgs }}"
  when: '"apt" in ansible_pkg_mgr'

- name: Enable dovecot service
  become: true
  service:
    name: dovecot
    enabled: true
    state: started
