---

- name: Install dovecot packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ dovecot_apt_pkgs }}"
  when: '"apt" in ansible_pkg_mgr'

- name: Enable or disable the dovecot service
  become: true
  service:
    name: dovecot
    enabled: "{{ enable_dovecot_service | default('true') }}"
    state: started
