---
# tasks file for dovecot
- include_tasks: install.yml
- include_tasks: configure.yml
- include_tasks: ssl.yml
  when: (do_ssl|bool) and (! do_ssl_ami|bool)
- include_tasks: ssl_ami.yml
  when: (! do_ssl|bool) and (do_ssl_ami|bool)
- include_tasks: users.yml
  when: do_ldap_users|bool
- include_tasks: ldap.yml
  when: do_ldap|bool
